### ISSUE TITLE
mover a elasticsearch

### ISSUE THREAD

**Issue by aniversarioperu** [aniversarioperu/django-manolo#1]

**Comment by orioloremor** [comment]
Hey boy!!
R u moving ur database to an independente Elastic Search Server - in a Digital Ocean droplet- or to a standard service provider -f.e. Amazon-?

This change going to be permanent?
Good luck! -there are good sample project in Packtpub books-

**Comment by aniversarioperu** [comment]
most likely permanent move to elasticsearch in private virtualserver.

are you a bot?

**Comment by aniversarioperu** [comment]
closed by 0b75b81797cc0b589389c7ae1d788de739fb4bcb
